version: "3.8"

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./data:/home/dynamodblocal/data
    command:
      -jar DynamoDBLocal.jar
      -sharedDb
      -dbPath /home/dynamodblocal/data
      -cors "*"
    networks:
      - dynamodb-network

networks:
  dynamodb-network:
    driver: bridge